name: Rust

on:
  workflow_dispatch:
    ~

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./lsp
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./lsp
      run: cargo test --verbose
